spring.datasource.url=jdbc:mysql://localhost:3306/academia
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.servlet.multipart.max-file-size=30MB
spring.servlet.multipart.max-request-size=30MB
spring.jpa.show-sql=true
file.upload-dir-user=uploads/users
file.upload-dir-exercicio=uploads/exercicios
file.upload-dir-produto=uploads/produtos

abacate.api.url=https://api.abacatepay.com/v2
abacate.api.key=${ABACATE_API_KEY}
abacate.webhook.secret=${ABACATE_WEBHOOK_SECRET}